# Env vars in here should be replaced using envsubst before rendering the chart
replicaCount: 1
autoscaling:
  enabled: false

image:
  repository: "${DOCKER_REGISTRY}/triggir"
  pullPolicy: Always
  tag: "${IMAGE_TAG}"

serviceAccount:
  create: true

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  containerPort: 4000

ingress:
  enabled: true
  hosts:
    - host: "${HOSTNAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific

# TODO: persistent volume setup
runOutputRoot: "/run-output"

secrets:
  # sshPrivateKey Use --set to pass this value
  sshPrivateKey:
  # knownHosts Use --set to pass this value
  knownHosts:

### Subcharts ###
docker-in-docker:
  secureDocker: false

influxdb:
  image:
    tag: "2.7-alpine"
  env:
    # NOTE: use the relative .Values path for the subchart
    - name: DOCKER_INFLUXDB_INIT_PASSWORD
      value: "{{ .Values.secret.password }}"
    - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      value: "{{ .Values.secret.token }}"
    - name: DOCKER_INFLUXDB_INIT_MODE
      value: setup
    - name: DOCKER_INFLUXDB_INIT_USERNAME
      value: influx
    - name: DOCKER_INFLUXDB_INIT_ORG
      value: triggir
    - name: DOCKER_INFLUXDB_INIT_BUCKET
      value: phoenix
    - name: DOCKER_INFLUXDB_INIT_RETENTION
      value: 4w
