---
- type: bash
  body: |
    set -euo pipefail

    git clone "$REPOSITORY_URL" || true
    pushd "$REPOSITORY_NAME"
    git fetch
    popd

    git clone "$REPOSITORY_NAME" "$WORKDIR"
    pushd "$WORKDIR"
    git checkout "$CHECKOUT_SHA"
    git remote remove origin
    git remote add origin "$REPOSITORY_URL"
