apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  MIX_ENV: "prod"
  RUN_OUTPUT_ROOT: "{{ .Values.runOutputRoot }}"
  PHX_SERVER: "true"
  {{- if .Values.environment }}
{{ .Values.environment | toYaml | indent 2 }}
  {{- end }}
