apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-git-priv-ssh-key"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    {{ b64enc .Values.secrets.sshPrivateKey }}
    
  known_hosts: |
    {{ b64enc .Values.secrets.knownHosts }}
    

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret-config"
stringData:
  POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
  {{- if .Values.environment }}
{{ tpl (.Values.secretEnvironment | toYaml | indent 2) . }}
  {{- end }}
