apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-git-priv-ssh-key"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    {{ b64enc .Values.secrets.sshPrivateKey }}
    
  known_hosts: |
    {{ b64enc .Values.secrets.knownHosts }}
    

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret-config"
stringData:
  PG_USER: {{ .Values.postgresql.auth.username }}
  PG_PASS: {{ .Values.postgresql.auth.password }}
  PG_DB: {{ .Values.postgresql.auth.database }}
  {{- if .Values.environment }}
{{ .Values.secretEnvironment | toYaml | indent 2 }}
  {{- end }}
